baseURL = "http://example.org/"
languageCode = "zh-cn"
title = "Yeka's Blog"
theme = "hugo-notepadium"
copyright = "©2019 lyeka."
summaryLength = 70



[params]
style = "dark"
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = "logo.jpg"  # if you have a logo png
slogan = "做三月份的事，七月份自有答案"
license = ""  # CC License
fullRss = false # Puts entire HTML post into rss 'description' tag. If unset, default is false.


[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

# custom navigation items

[[params.nav.custom]]